# Generated by Django 3.2.20 on 2023-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_authentication_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
