# Generated by Django 3.2.20 on 2023-07-15 06:08

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField()),
                ('location', models.TextField()),
                ('availibility', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
            ],
        ),
    ]
