import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins, Playfair_Display } from 'next/font/google'
import Navbar from './Components/Navbar/NavBar'
import Footer from './Components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['300','500','700'] })
const playfairDisplay = Playfair_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container">
        <Navbar/>
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
