# Generated by Django 3.2.20 on 2023-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='seats',
            field=models.CharField(max_length=50),
        ),
    ]
